apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: board

resources:
  - ../namespace.yaml
  - ../secrets/sealed/postgres-credentials.yaml
  - ../secrets/sealed/keycloak-admin.yaml
  - ../keycloak/deployment.yaml
  - ../user-service/deployment.yaml
  - ../book-service/deployment.yaml
  - ../group-service/deployment.yaml
  - ../feedback-service/deployment.yaml
  - ../kong/deployment.yaml
  - ../frontend/deployment.yaml
  - ../ingress/board-platform.yaml

configMapGenerator:
  - name: keycloak-config
    files:
      - realm-board.json=../../keycloak/realm-board.json
      - board-user-profile.json=../../keycloak/board-user-profile.json
      - entrypoint-custom.sh=../../keycloak/entrypoint.sh

