---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-admin
  namespace: board
spec:
  encryptedData:
    password: AgAKrkPAJCCB5lwQyk5X87b9qwxVox1MEAOejTg1yFO7IGT7MRPXPX2nNYMl7UWvLAdHPjfvj2A/0Q3j/00bJTpUufv38Z3ikNGwIub+LZlEfJ4dk4fKmhVJqMpHoTgqrsONyfBYEM6zOg4AXqW0n77hn08a5qiu7SKC3b+ZWvKkzGwuXuRA0+e7uET0DjEtx3ONYKifGtT6KtpXf9lNOOieR2k6JOxslEmOoXdBbpsvbEpfSj0S5fl+ptVP7EPtwn/7HG+AXwC7yMoWN2z5vEn/fQTINUGAuDIzrfYti5vouyqtLO4VmQ3dlGpecCPsNHTj9Y1IUlWVY4N4/Vc3xDgt7s8TPKkt3+KhRGAvQ41FjdCNwppqzcwfH9VU6XKU9ocS6Pf5lSyl1cjciLS80rEu/cvg7KxBZBozV3DW9BAGYvfA6PZyCVwjsCQDV9WdB+ykZprYqz4qrRm+issTCut5ADqwGWvuXiMEGQNxnvv+G1mtprP7OyRsaEspyhWSulpG/VWPdhEy7a9nqXAYM3Bzlvlcw9xzwmnemlUiXOdArJW4n5FrPMWa6DqXg6kDsH9gbh0GZM/EocPFRuG0Ylb7DU+lnKD5kBXOfue6EA6NwA+JZ81eWMmiWU2xb57/6i3HhSKYoCZ6emj5SCViJ0eifx6rhBJ4wctUiot1s+ghZNEKIvkSa52kG9ElvNcmgnwdjWeFSA==
    username: AgB6HCNrqd6QmY8dDn2FL6vn8piuF6BDscQUcYkOrFZhZOb1L5T+IB0LNY0nAvQNu7NUK/anZrTjNb/3DTh1gGOUB0t+tp/vFPktKvN8nLRN7s6pf5UOS53+3aJN0YCbfN/FvnnJYUPHLJ1IWSORYRMeFX/U48HouJP9bxMP3M79t7EYtbqxDLTqJ8j25FMWvCr1kO3+vk3fCupuqni/kHisFmPTrTq7tFCw7xyCr10QvdzjQthwHI2Q3CvkxwDOYDOWNzu59MMOuNUBkCsdJWLB1cbPIbFAIQkk6hSuPzxvjIApznhO9JAjXZ6zESYwt8wGeSjoKpuV19Q6tbKwcPp0MGzMoDyABcfolGoKAtXUtcxvP53TB6Zzx61X0hcz/3kYviPxsOp2LcXpog+qain+Eucr9yuLm6yWzLYkgTSt1KdBcOMLgRpr0iPu6+efZrZM7kjt8tXFklYEYIrQpsB8S0Kd1QVoHbWib9QqIqbTtA1Hnvx9qId6dSgqOfUqvLPsmCUQlWEwgmmffbx6g56nygRZw/r7wy0P2GFpfxChaKnuli/1CniY9PBlnvzGXRWYErXhmDUc6ZU6U/iQg5JDqDwpV3XcL4iueBF0s1iMiK87XCiRMEaTQ5NdxLq2qXUlMxwa/ganTvopukvSCvrTjvlMdAtKlglZ4eqbJTxX4MzgbDUbhMWmGjG2XTiLRIoEekRUxA==
  template:
    metadata:
      creationTimestamp: null
      name: keycloak-admin
      namespace: board
