---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-admin
  namespace: board
spec:
  encryptedData:
    password: AgACl/JQphduH9eJHiD6XPof9Dhvs4dl9sFV1Kjf8XMT0PN96yjOD9Rlrgw8bFsRKsdlqidL1oatDT8LkHBhkkZ6So8GztNNNInIch3jWEFewFDnWAtnJDLGeKv4fxLs/+UgXwTB/+lGdf7vKm7ti/n4eANnCTjbkcgfklYPUYW3+AhhIzWmxW5SYt22lu5K5pWkr3rj6EASmxAVgoYbdN0O9azbYvyNmpsG5A4rHgQXgeAUl34Gni1yqzlcUhSF5G+Vd8Y9ws7DArPWt4trDYFCivzF6dUuovpeooNcRMLqTjwWv44dOORlKxnmSY0lrOsk9hkT+ExrRMHoZxGLpbtF/LttstiZdey1BqBD8CpKpVKZYivn9H2u7SmceoG2Vneu1BJwAzUNuNFwa3BbGUsFetrt6kgZIFCHNnfOqQj7zbNwkTOSWB8NkRwxVg5Ezl6nxr46mnpqB9/UncYXeddBf71Srw/xmeaZLcGd29jS78D/F14Vbz54JW98n/FL8XaB8mtdxRmiOEwhMLx+WubU1yd1VuYmHliPLZ6ZaUlANvChlkbzpW1rQXRCGwaotK/rn3ExZ0UFSQ0m7s+lJaqbW2NL17ev8Zl/lJlk0HwIbwpnhuAtgaNPjun/Neij/OdPBGNEO6CSYo8L22Ys7L0oeiTH54FiArxU7U11M1MXeEkrVHNYy6kBszgUvK1QvpoKCBWhPA==
    username: AgCHck1VyDAN1On+OMmZ7xIVLON2US/4bNrKrVDqKjioNSjmTmi7hwU0bqaPymUmAwtxRnkbT0IYJMR5TWhWd2G+7+OskHW28bLEFwRlyWVieVHbkomOghdBwvU0+olLacDrQ61IT6JKejD/kAO152860jbompEudgwzThQHMoOARHtmeymeO384wSJykZKmn7u4p7KoaobN7m/cZxFlid5j9MVCx3X7smZ7Inky5ztKexOoDdrvyomYfXYpcZXXXuq0xwlmKZ2qjTFtN9t0b/Fv0hZZbH3Opoh7/sv2xCmifoHtUzS7G58sUF/8En73bM5D7iYO621z6DQAYfV2qinP7TDLc7h1hI5llxyv/gSTNL1S3a6psmtOsq4DyOOd6/vB//DCwhXoHPLccyObITd8bzXUsyDGQxNR0e3YcSMXwHybJAmr8aRYYfU0UoHWcqiQwanHxIifYEct1bxwrTVHgRxAfHUyfRlWY/WaJ+cKahKyqqJ40rMCkua2JKGWOdGF2bKr8qtXVkNsw8Cp/iS8S/+47/WAIyIgDwkxYgDEG1h+CPYtllmSivw4eIM5Fo7HXWAENZV4g/a6qe/4vq/PUuTM+llZlzgetHPGzNyl3imaPsNdHr3pLCz5OvqDd5XXQfTNKUxwKxsxh0XGFN+C4BM74iswLq0QC+Wabc2H5Z2zLzA8xtoKQRILSwHi6nGj3N36/g==
  template:
    metadata:
      creationTimestamp: null
      name: keycloak-admin
      namespace: board
